### ISSUE TITLE
Why using Git version instead of packages on Sourceforge ?

### ISSUE THREAD

**Issue by jbz-dev** [KaOS-Community-Packages/wesnoth#1]
Hi, I wanted to install Wesnoth (love that game) and I noticed that your PKGBUILD uses Git version to build the game.
It takes a lot of time to clone the git repo and I found that you can use Wesnoth packages on Sourceforge in your PKGBUILD instead of Git.
I did that and it works perfectly. 

Don't know if you want to switch from git to sourceforge's pkgs but if you're OK, I can push the new PKGBUILD.

**Comment by tesrtasr** [comment]
Heya, I don't mind if you switch the PKGBUILD source from git to an archive. Have a speedy internet connection so that this could be a problem never occurred to me.
