### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by pasnox** [KaOS-Community-Packages/wesnoth#2]
This package is broken and don't build with kaos as of May 8 2018.
Please fix it (and ugrade it ;))

**Comment by ShalokShalom** [comment]
You may wanna try to upgrade it by coping the PKGBUILD to your device, changing the version number and running first makepkg -g and then makepkg -si in the same folder/directory where you store the PKGBUILD. After the makepkg -g, simply copy and replace the result into the PKGBUILD and save that. I am currently without access to my laptop, somebody else might upgrade it for you. You can see this as an opportunity to step into the world of packaging and I am sure, we can help you on your adventures :D

**Comment by pasnox** [comment]
Fixed. Upgraded to version 1.14.1 as well.
